Jenkins系列视频~流水线语法-part3字幕文件
jenkins-zh/jenkins-open-tutorial pull request #24
Opened 2020-11-03 12:51 UTC by ZhzhIn

添加 Jenkins系列视频~流水线语法-part3的字幕文件

2020-11-04 00:18 UTC, LinuxSuRen commented
@yJunS 你有校对过吗？

2020-11-05 15:57 UTC, yJunS commented
这个我还没校对过，我周五晚上校对一下看看吧

2020-11-06 00:59 UTC, LinuxSuRen commented
> 这个我还没校对过，我周五晚上校对一下看看吧

好的，校对完成后就给个approve，辛苦了。

2020-11-07 01:43 UTC, yJunS requested changes
有一些问题需要修改一下，有些断句尽量还是用空格间隔一下

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +只要变更那么就触发了
听着是 “触发流水线”

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +因为可能是关键
`关键` -> `构建出`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +是最后一个来就可以了
`是最后一个` -> `最后一个`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +我们会在具体的章节那边继续分享
`继续分享` -> `去分享`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +就是这个除了我们所能触发以外
`所能触发`-> `手动触发`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +触发就是说
`触发` -> `触发器`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +比如说我就得十点整的时候我执行
`我执行` -> `会运行`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +其实是10 01
`10 01` -> `10点01分`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +10 02也没有关系
`10 02` -> `10点02分`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +整个流程已经失败了
`流程已经失败` -> `流水线就失败`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +有些情况可能我们不希望就是能失败
`就是能` -> `流水线`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +这里一个person，在这里引用了这个参数
`在这里引用了这个参数` -> `这拿变量来取它`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +你也可以写个表达式的吧
`表达式的吧` -> `表达式对吧`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +我在三个平台上构建
`我在三个平台上构建` 前面 加一个 `构建 `

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +那么如果你要写死在这的话
`死在这` -> `stage`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +很很难一起维护
`很难一起` -> `很难以去`

2020-11-07 01:43 UTC, yJunS commented on openshot/jenkins-pipeline-syntax-part3.srt
> +接下来仔细看
`仔细看` -> `自己去看一下`

2020-11-12 15:18 UTC, yJunS approved these changes

2020-11-13 00:41 UTC, LinuxSuRen commented
Thank you @ZhzhIn  and @yJunS

2020-11-13 00:41 UTC, merged